language: cpp
compiler:
  - clang
  - gcc
os: linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - gcc-6
      - g++-6
      - clang-3.9
      - liblua5.2-dev
branches:
  only:
    - master
before_install:
  - wget --no-check-certificate https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz
  - tar xf cmake-3.7.2-Linux-x86_64.tar.gz
  - git submodule update --init --recursive
  - mkdir install
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.9" CC="clang-3.9"; fi
  - ./cmake-3.7.2-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_BUILD_TYPE=Release .
install:
  - make -j
