language: c++

sudo: false

cache:
  directories:
    - deps/cmake
    - deps/lcov
    - deps/llvm-3.9.0

addons:
  apt:
    packages:
      - g++-6
      - liblua5.2-dev
      - lcov
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      env: COMPILER=g++-6
      compiler: gcc

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  - if [[ "$COMPILER" != "" ]]; then export CXX=${COMPILER}; fi

  - CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
  - travis_retry wget --no-check-certificate -qO - ${CMAKE_URL} | tar xz --strip-components=1 -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version

  - LCOV_URL="http://downloads.sourceforge.net/ltp/lcov-1.13.tar.gz"
  - travis_retry wget --no-check-certificate -qO - ${LCOV_URL} | tar xz --strip-components=1 -C lcov
  - export PATH=${DEPS_DIR}/lcov/bin:${PATH}
  - lcov --version

  - ${CXX} --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_CODECOVERAGE=ON

script:
  make -j && make test

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - lcov --gcov-tool "gcov-6" --capture --directory .. --output-file coverage.info
  - lcov --gcov-tool "gcov-6" --remove coverage.info '/usr/*' $TRAVIS_BUILD_DIR'/libs/*' --output-file coverage.info
  - lcov --gcov-tool "gcov-6" --list coverage.info
  - bash <(curl -s https://codecov.io/bash)
